import { useMemo,useState } from 'react';
import { Box,Button,MenuItem,Select,TextField,Typography } from '@mui/material';
import './AdminReports.css';

const money=(value)=>`₹${Number(value||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`;
const AdminReports=({orders,customers,products,inventory,stores})=>{
  const [from,setFrom]=useState('');const [to,setTo]=useState('');const [location,setLocation]=useState('All');const [store,setStore]=useState('All');const [sort,setSort]=useState('revenue');
  const locations=[...new Set(stores.map((item)=>item.location).filter(Boolean))].sort();
  const selectableStores=stores.filter((item)=>location==='All'||item.location===location).sort((a,b)=>a.name.localeCompare(b.name));
  const filtered=useMemo(()=>orders.filter((order)=>{const date=new Date(order.createdAt);return(!from||date>=new Date(`${from}T00:00:00`))&&(!to||date<=new Date(`${to}T23:59:59`))&&(location==='All'||order.sourceLocation===location||order.location===location)&&(store==='All'||order.sourceStore===store||order.store===store||order.fulfilmentAssignments?.some((item)=>item.store===store));}),[orders,from,to,location,store]);
  const revenue=filtered.filter((item)=>item.status!=='Cancelled').reduce((sum,item)=>sum+Number(item.total||0),0);const delivered=filtered.filter((item)=>item.status==='Delivered').length;
  const performance=selectableStores.map((item)=>{const rows=orders.filter((order)=>order.sourceStore===item.name||order.store===item.name||order.fulfilmentAssignments?.some((assignment)=>assignment.store===item.name));return {name:item.name,location:item.location,orders:rows.length,revenue:rows.filter((row)=>row.status!=='Cancelled').reduce((sum,row)=>sum+Number(row.total||0),0)};}).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='orders'?b.orders-a.orders:b.revenue-a.revenue);
  const reset=()=>{setFrom('');setTo('');setLocation('All');setStore('All');setSort('revenue');};
  const exportReport=()=>{const payload={filters:{from,to,location,store,sort},summary:{orders:filtered.length,revenue,delivered},storePerformance:performance,orders:filtered};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='scoped-report.json';link.click();URL.revokeObjectURL(url);};
  return <Box className="reports-dashboard"><Box className="reports-filters"><TextField label="From" type="date" size="small" value={from} onChange={(e)=>setFrom(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField label="To" type="date" size="small" value={to} onChange={(e)=>setTo(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><Select size="small" value={location} onChange={(e)=>{setLocation(e.target.value);setStore('All');}}><MenuItem value="All">All locations</MenuItem>{locations.map((name)=><MenuItem key={name} value={name}>{name}</MenuItem>)}</Select><Select size="small" value={store} onChange={(e)=>setStore(e.target.value)}><MenuItem value="All">All stores in location</MenuItem>{selectableStores.map((item)=><MenuItem key={item.id} value={item.name}>{item.name}</MenuItem>)}</Select><Select size="small" value={sort} onChange={(e)=>setSort(e.target.value)}><MenuItem value="revenue">Sort stores by revenue</MenuItem><MenuItem value="orders">Sort stores by orders</MenuItem><MenuItem value="name">Sort stores by name</MenuItem></Select><Button onClick={reset}>Reset</Button><Button variant="contained" onClick={exportReport}>Export</Button></Box><Box className="reports-kpis">{[['Revenue',money(revenue)],['Orders',filtered.length],['Delivered',delivered],['Customers',customers.length],['Products',products.length],['Stock Units',inventory.reduce((sum,item)=>sum+Number(item.stock||0),0)]].map(([label,value])=><Box className="reports-kpi" key={label}><Typography>{label}</Typography><Typography variant="h5">{value}</Typography><small>{store!=='All'?store:location!=='All'?location:'All business data'}</small></Box>)}</Box><Box className="report-card" sx={{mt:2}}><Typography variant="h6" fontWeight={800}>Store performance</Typography><Box className="analytics-table"><header><span>Store and location</span><span>Orders</span><span>Revenue</span></header>{performance.map((item)=><div key={item.name}><span>{item.name}<small style={{display:'block'}}>{item.location}</small></span><span>{item.orders}</span><strong>{money(item.revenue)}</strong></div>)}</Box></Box></Box>;
};
export default AdminReports;
