import { useMemo,useState } from 'react';
import { Alert,Box,Button,Chip,MenuItem,Select,Typography } from '@mui/material';
import { useNavigate } from 'react-router-dom';
import { orderStore } from '../../services/localDataService';

const GlobalStoreAssignment=({orderId})=>{
  const navigate=useNavigate();const order=orderStore.list().find((item)=>item.id===orderId);const options=useMemo(()=>orderStore.globalStoreOptions(orderId),[orderId]);const [storeId,setStoreId]=useState('');const [message,setMessage]=useState('');const selected=options.find((item)=>item.store.id===storeId);
  if(!order)return <Box p={4}><Typography variant="h5">Order not found</Typography><Button onClick={()=>navigate('/admin/orders')}>Back</Button></Box>;
  const assign=()=>{try{orderStore.assignGlobalStore(orderId,storeId);navigate('/admin/orders',{replace:true});}catch(error){setMessage(error.message);}};
  return <Box sx={{position:'fixed',inset:0,zIndex:1400,bgcolor:'rgba(15,23,42,.6)',p:{xs:2,md:4},overflowY:'auto'}}><Box sx={{maxWidth:900,mx:'auto',bgcolor:'white',p:{xs:2,md:4},borderRadius:3,boxShadow:24}}><Button onClick={()=>navigate('/admin/orders')}>Close</Button><Typography variant="h4" fontWeight={800} mt={2}>Assign stocked store</Typography><Typography color="text.secondary">Only stores that can fulfil the complete product group are listed, nearest to farthest.</Typography><Box sx={{display:'grid',gridTemplateColumns:{md:'1fr 1fr'},gap:2,my:3}}><Box sx={{p:2,bgcolor:'#f8fafc',borderRadius:2}}><Typography fontWeight={800}>User location</Typography><Typography>{order.customer?.name} · {order.customer?.phone}</Typography><Typography>{order.checkout?.deliveryAddress}</Typography><Chip sx={{mt:1}} label={order.destinationLocation||order.checkout?.customerLocation||'Unknown'}/></Box><Box sx={{p:2,bgcolor:'#f8fafc',borderRadius:2}}><Typography fontWeight={800}>Product group</Typography>{order.items?.map((item)=><Typography key={item.id}>{item.title} × {item.quantity}</Typography>)}</Box></Box>{!options.length?<Alert severity="warning">No active store has enough stock for this complete order.</Alert>:<><Select fullWidth displayEmpty value={storeId} onChange={(event)=>setStoreId(event.target.value)}><MenuItem value="" disabled>Select location and store</MenuItem>{options.map(({store,distanceLabel})=><MenuItem key={store.id} value={store.id}>{distanceLabel} — {store.name} — {store.area?`${store.area}, `:''}{store.location}, {store.state}</MenuItem>)}</Select>{selected&&<Box sx={{mt:2,p:2,border:'1px solid #dce9e3',borderRadius:2}}><Typography fontWeight={800}>{selected.distanceLabel}</Typography><Typography>{selected.store.name}</Typography><Typography>{selected.store.address}</Typography>{selected.matches.map(({requested,stock})=><Typography key={requested.id}>{requested.title}: {stock} available / {requested.quantity} needed</Typography>)}</Box>}<Button sx={{mt:3}} variant="contained" disabled={!storeId} onClick={assign}>Confirm store assignment</Button></>}{message&&<Alert severity="error" sx={{mt:2}}>{message}</Alert>}</Box></Box>;
};
export default GlobalStoreAssignment;
